USE ROLE ACCOUNTADMIN;
USE SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS;
USE WAREHOUSE AI_MEDIA_WH;

CREATE OR REPLACE TABLE VIDEO_CATALOG AS
SELECT
    TO_FILE('@VIDEO_STAGE', RELATIVE_PATH) AS video_file,
    RELATIVE_PATH AS file_path,
    SPLIT_PART(RELATIVE_PATH, '/', -1) AS file_name,
    SIZE AS file_size_bytes,
    LAST_MODIFIED AS ingested_at
FROM DIRECTORY(@VIDEO_STAGE);

CREATE OR REPLACE TABLE AUDIO_CATALOG AS
SELECT
    TO_FILE('@AUDIO_STAGE', RELATIVE_PATH) AS audio_file,
    RELATIVE_PATH AS file_path,
    SPLIT_PART(RELATIVE_PATH, '/', -1) AS file_name,
    SIZE AS file_size_bytes,
    LAST_MODIFIED AS ingested_at
FROM DIRECTORY(@AUDIO_STAGE);

CREATE OR REPLACE STREAM VIDEO_STAGE_STREAM ON STAGE VIDEO_STAGE;
CREATE OR REPLACE STREAM AUDIO_STAGE_STREAM ON STAGE AUDIO_STAGE;

CREATE OR REPLACE TASK SYNC_VIDEO_CATALOG
    WAREHOUSE = AI_MEDIA_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('VIDEO_STAGE_STREAM')
AS
    INSERT INTO VIDEO_CATALOG (video_file, file_path, file_name, file_size_bytes, ingested_at)
    SELECT
        TO_FILE('@VIDEO_STAGE', RELATIVE_PATH),
        RELATIVE_PATH,
        SPLIT_PART(RELATIVE_PATH, '/', -1),
        SIZE,
        LAST_MODIFIED
    FROM VIDEO_STAGE_STREAM
    WHERE METADATA$ACTION = 'INSERT';

CREATE OR REPLACE TASK SYNC_AUDIO_CATALOG
    WAREHOUSE = AI_MEDIA_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('AUDIO_STAGE_STREAM')
AS
    INSERT INTO AUDIO_CATALOG (audio_file, file_path, file_name, file_size_bytes, ingested_at)
    SELECT
        TO_FILE('@AUDIO_STAGE', RELATIVE_PATH),
        RELATIVE_PATH,
        SPLIT_PART(RELATIVE_PATH, '/', -1),
        SIZE,
        LAST_MODIFIED
    FROM AUDIO_STAGE_STREAM
    WHERE METADATA$ACTION = 'INSERT';

ALTER TASK SYNC_VIDEO_CATALOG RESUME;
ALTER TASK SYNC_AUDIO_CATALOG RESUME;