USE ROLE ACCOUNTADMIN;
USE SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS;
USE WAREHOUSE AI_MEDIA_WH;

CREATE ROLE IF NOT EXISTS MEDIA_ANALYST;
CREATE ROLE IF NOT EXISTS MEDIA_MODERATOR;
CREATE ROLE IF NOT EXISTS MEDIA_ADMIN;

-- Analysts: read access to views and tables
GRANT SELECT ON ALL VIEWS IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ANALYST;

-- Moderators: safety table + summary view
GRANT SELECT ON TABLE CONTENT_MODERATION_RESULTS TO ROLE MEDIA_MODERATOR;
GRANT SELECT ON VIEW V_CONTENT_SAFETY_SUMMARY TO ROLE MEDIA_MODERATOR;

-- Admins: inherit analyst + moderator roles
GRANT ROLE MEDIA_ANALYST TO ROLE MEDIA_ADMIN;
GRANT ROLE MEDIA_MODERATOR TO ROLE MEDIA_ADMIN;
GRANT ALL ON SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ADMIN;
GRANT ROLE MEDIA_ADMIN TO ROLE SYSADMIN;

-- Admins: warehouse usage for manual procedure execution
GRANT USAGE ON WAREHOUSE AI_MEDIA_WH TO ROLE MEDIA_ADMIN;

-- Admins: execute stored procedures (manual re-runs)
GRANT USAGE ON PROCEDURE ANALYZE_BRAND_SENTIMENT() TO ROLE MEDIA_ADMIN;
GRANT USAGE ON PROCEDURE ANALYZE_PRODUCT_TRENDS() TO ROLE MEDIA_ADMIN;
GRANT USAGE ON PROCEDURE ANALYZE_COMPLIANCE() TO ROLE MEDIA_ADMIN;
GRANT USAGE ON PROCEDURE ANALYZE_CONTENT_MODERATION() TO ROLE MEDIA_ADMIN;
GRANT USAGE ON PROCEDURE TRANSCRIBE_AUDIO() TO ROLE MEDIA_ADMIN;
GRANT USAGE ON PROCEDURE ANALYZE_AUDIO_BRAND_MENTIONS() TO ROLE MEDIA_ADMIN;
GRANT USAGE ON PROCEDURE TRANSCRIBE_VIDEO() TO ROLE MEDIA_ADMIN;
GRANT USAGE ON PROCEDURE ANALYZE_VIDEO_BRAND_MENTIONS() TO ROLE MEDIA_ADMIN;

-- Admins: monitor and operate tasks (suspend/resume/check history)
GRANT MONITOR, OPERATE ON ALL TASKS IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ADMIN;

-- Analysts: read access to streams (view change data)
GRANT SELECT ON ALL STREAMS IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ANALYST;

-- Future grants: auto-apply privileges to new objects
GRANT SELECT ON FUTURE TABLES IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ANALYST;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ANALYST;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ADMIN;
GRANT MONITOR, OPERATE ON FUTURE TASKS IN SCHEMA MEDIA_INTELLIGENCE.BRAND_INSIGHTS TO ROLE MEDIA_ADMIN;
