USE ROLE ACCOUNTADMIN;

DROP DATABASE IF EXISTS MEDIA_INTELLIGENCE;
DROP WAREHOUSE IF EXISTS AI_MEDIA_WH;

DROP ROLE IF EXISTS MEDIA_ANALYST;
DROP ROLE IF EXISTS MEDIA_MODERATOR;
DROP ROLE IF EXISTS MEDIA_ADMIN;